---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: heketi
  labels:
    glusterfs: heketi-deployment
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: 1
  template:
    metadata:
      name: heketi
      labels:
        name: heketi
        glusterfs: heketi-pod
    spec:
      containers:
      - image: heketi/heketi:dev
        imagePullPolicy: Always
        name: heketi
        env:
        - name: HEKETI_EXECUTOR
          value: kubernetes
        - name: HEKETI_KUBE_USE_SECRET
          value: y
        - name: HEKETI_KUBE_TOKENFILE
          value: "/var/lib/heketi/secret/token"
        - name: HEKETI_KUBE_NAMESPACEFILE
          value: "/var/lib/heketi/secret/namespace"
        - name: HEKETI_FSTAB
          value: "/var/lib/heketi/fstab"
        - name: HEKETI_SNAPSHOT_LIMIT
          value: '14'
        - name: HEKETI_KUBE_INSECURE
          value: y
        - name: HEKETI_KUBE_APIHOST
          value: {{master_api}}
        - name: HEKETI_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HEKETI_KUBE_GLUSTER_DAEMONSET
          value: y
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db
          mountPath: "/var/lib/heketi"
        - name: secret
          mountPath: "/var/lib/heketi/secret"
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: heketi
      - name: secret
        secret:
          secretName: {{secret_name}}
